### ISSUE TITLE
[bug] IDE Extension triggering message changes by itself

### ISSUE THREAD

**Issue by tomas-correia** [inlang/monorepo#1929]
### Problem

I'm using ParaglideJS, and after installing the extension and using the `Inlang: Extract Message` action, I'll stand still, literally do nothing and the extension will keep changing the `messages.js` file on a loop.

It's not actually changing anything in the content, but it's triggering file changes, so ParaglideJS keeps recompiling, causing Vite to keep reloading the page.

Everywhere I use my message functions, they flash warning squiggly lines, which keep appearing and disappearing repeatedly.

### Expected behavior

Not triggering message changes and flashing things everywhere.

### Reproduction

I don't think you need any special code to reproduce this, but this should be enough to trigger it:
```svelte
<!-- +page.svelte -->
<script>
    import * as m from "$paraglide/messages"
</script>

<title>My Website | {m.page_home_title()}</title>
```
```json
// en.json
{
    "$schema": "https://inlang.com/schema/inlang-message-format",
    "page_home_title": "Welcome!"
}
```
```json
// pt.json
{
    "$schema": "https://inlang.com/schema/inlang-message-format",
    "page_home_title": "Bem-vindo!"
}
```

### Other information

I'm on Windows 11.

Video of the issue:
https://github.com/inlang/monorepo/assets/20492365/10df5ae1-db7e-4b32-9824-83c77e45f11c

**Comment by felixhaeberle** [comment]
see this discord thread on the reactivity issue: https://discord.com/channels/897438559458430986/1070750156644962434/1187173431196782703

**Comment by felixhaeberle** [comment]
also maybe @LorisSigrist can give insights why messages.js constantly changes.

**Comment by LorisSigrist** [comment]
Paraglide recompiles whenever the SDK detects that the message-files (`./messages/en.json` etc) have changed. 
The SDK detects this in a very naive way, where it just listens to `fs.watch` and doesn't check if the content actually changed. `fs.watch` triggers whenever an OS file API is used on the file, which on windows is quite often. That could cause an infinite loop

For now we have a patch-solution where Paraglide checks if the messages have changed since it last compiled, but that should really be an SDK feature. I'll trigger a release with this patch & then this should be fixed

**Comment by jamesbirtles** [comment]
For what its worth this just started happening to me too, on Mac OS Sonoma 14.1 (M2)

**Comment by felixhaeberle** [comment]
For Mac users, please downgrade the extension to 1.22 in the meantime, this will fix it for you. 
For those running on Windows, we are currently working on a fix!

cc @NiklasBuchfink

**Comment by Gernii** [comment]
For Linux (ubuntu) SSH downgrade the extension to 1.22 doesn't fix the bug
OS version: 20.04.3 LTS
[25af9d9e-2180-4a31-a85e-9855337e4da4.webm](https://github.com/inlang/monorepo/assets/54741529/990aeafc-b4df-4862-b154-ef7ffeb8f0a3)
